export const GROUP_NOT_FOUND = 'GROUP_NOT_FOUND';
export const GROUP_INVALID = 'GROUP_INVALID';

export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_INVALID = 'USER_INVALID';
export const USER_GROUP_NOT_FOUND = 'USER_GROUP_NOT_FOUND';

export const FORBIDDEN = 'FORBIDDEN';
