export const GROUP_NOT_FOUND = 'GROUP_NOT_FOUND';
export const GROUP_INVALID = 'GROUP_INVALID';

export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_NOT_REGISTERED = 'USER_NOT_REGISTERED';
export const USER_HAS_NO_GROUP = 'USER_HAS_NO_GROUP';
