version: '3.7'

services:

  server:
    build:
      target: production
    command: bash -c 'while !</dev/tcp/database/5555; do sleep 1; done; yarn start:prod;'

  database:
    volumes:
      - ./init-database.prod.sh:/docker-entrypoint-initdb.d/init-database.sh

  client:
    build:
      target: production
    command: bash -c 'yarn start:prod;'
