version: '3.7'

services:

  server:
    container_name: server
    restart: unless-stopped
    build:
      context: ../server
      dockerfile: Dockerfile
    depends_on:
      - database
      - cache
    ports:
      - $SERVER_PORT:$SERVER_PORT
    env_file:
      - ../.env
    volumes:
      - ../server/src:/server/src
      - node_modules_server:/home/node/app/node_modules
    networks:
      - botnet

  database:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    ports:
      - $POSTGRES_PORT:5432
    env_file:
      - ../.env
    volumes:
      - ./volumes/database:/var/lib/postgresql/data:rw
    networks:
      - botnet
    command: -p $POSTGRES_PORT

  cache:
    container_name: cache
    image: memcached:latest
    restart: unless-stopped
    ports:
      - $MEMCACHED_PORT:11211
    volumes:
      - ./volumes/cache:/memcached
    networks:
      - botnet
    command: -p $MEMCACHED_PORT

  client:
    container_name: client
    restart: unless-stopped
    build:
      context: ../client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    env_file:
      - ../.env
    volumes:
      - ../client/src:/client/src
      - node_modules_client:/home/node/app/node_modules
    networks:
      - botnet

networks:
  botnet:
    driver: bridge

volumes:
  node_modules_server:
  node_modules_client:
